from enum import Enum


class TableName(str, Enum):
    OFFERS_RAW = "offers_raw"
    OFFER_PROFILES = "offer_profiles"
    OFFER_PROFILE_ELEMENTS = "offer_profile_elements"
    TARGET_AUDIENCES = "target_audiences"
    ANALYSIS = "analysis"
    OFFER_PROFILE_ANALYSIS = "offer_profile_analysis"
    ANALYSIS_QUESTIONS= "analysis_questions"
    QUESTION_ANSWERS = "question_answers"
    CHECKLIST = "checklist"
    CHECKLIST_ITEM = "checklist_item"
    ANALYSIS_CHECKLIST = "analysis_checklist"
    BRAND_MARKETING = "brand_marketing"
    MARKETING_STRATEGY = "marketing_strategy"
    OFFER_STRATEGY = "offer_strategy"
    MESSAGE_STRATEGY = "message_strategy"
    AD_STRATEGY = "ad_strategy"
    CREATIVE_STRATEGY = "creative_strategy"
    UGC_CREATIVES = "ugc_creatives"
    AD_SETUP = "ad_setup"
    CREATIVE_EXECUTION_SETUPS = "creative_execution_setups"
    GENERATE_ADS = "generate_ads"
    PAGE_STRATEGY = "page_strategy"
    PAGE_REQUIREMENTS = "page_requirements"
    PAGE_SECTION_REQUIREMENT = "page_section_requirement"
    PAGE_BLUEPRINT = "page_blueprint"
    PAGE_CONTENT_PLAN = "page_content_plan"
    PAGE_COPY = "page_copy"
    APP_OLLAMA_SETTINGS = "app_ollama_settings"
